name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  re-deploy:
    name: Re-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd gatherly && git pull
            npm install
            npm run build
            pm2 restart gatherly

